### ISSUE TITLE
Add a check in `animation_run` for when a track index is empty.

### ISSUE THREAD

**Issue by Manukineko** [KormexGit/GM-Animate#3]
Hello,
GM Animate assume that the first track created is always at index 0, but if I create a track at an higher index without setting track 0, `animation_run` will crash.
A safety check to ignore any empty track ( like
```gml
if animations[i] != 0{
    animations[i].__animate();
}
````
) would be useful.

**Comment by KormexGit** [comment]
Added a fix to the dev branch, will be in the next release. Realized I forgot to add the error check for not having an animations array at all, so added that as well. In the meantime you can leave your own fix in there to make it work.
Thank you for the report! (the first one, exciting!)
